import localFont from "next/font/local";
import "./globals.css";
import { Roboto } from 'next/font/google'

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const roboto= Roboto({
  subsets: ["latin"], // Specify the font subsets you need
  weight: ["100", "300", "400", "500", "700", "900"], // Specify the font weights you need
})
export const metadata = {
  title: "Movie Mania",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
